---
lumi:
  fInName: /Users/lucamicheletti/cernbox/JPSI/Psi2S_Jpsi_ratio_run3/data/LHC23_pass4_skimmed_minitree/AnalysisResults.root

yields:
  fInName: /Users/lucamicheletti/GITHUB/dq_fitter/analysis/LHC23_pass4_skimmed/unbinned_fit/output__minitree_Pt_2_20_CB2_CB2_VWG__2.4_4.6.root
  histName: sig_Psi2s_sw

axe:
  fInName: /Users/lucamicheletti/cernbox/JPSI/Run3/MC/LHC24e5/AnalysisResults_dq_efficiency_time_association.root
  histGenName: MCTruthGen_Psi2S
  histRecName: PairsMuonSEPM_matchedMchMid_mumuFromPsi2S
  kineMinCuts: [2, 2.5] # pT, rapidity
  kineMaxCuts: [20, 4] # pT, rapidity
  rebin: 4

crossSec:
  branchingRatio: 0.008
  label: "#psi(2S), pp@13.6TeV"
  ptCentrRun2: [2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 9.0, 11.0, 13.0, 15.0]
  ptWidthRun2: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0]
  crossSecRun2: [288.8, 169.9, 115.6, 71.99, 38.24, 25.03, 10.8, 4.168, 2.673, 1.298]
  statCrossSecRun2: [22.55, 16.64, 11.3, 7.378, 4.782, 3.478, 1.576, 0.983, 0.5774, 0.4617]
  labelRun2: "#psi(2S), pp@13TeV"

output:
  fOutName: "/Users/lucamicheletti/GITHUB/dq_run3_analyses/psi2S_jpsi_ratio/results/cross_section_psi2s_LHC23_pass4_skimmed"