---
prefilter:
  data: /Users/lucamicheletti/cernbox/JPSI/Psi2S_Jpsi_ratio_run3/data/LHC22p_pass7_skimmed_minitree/AO2D_merged_all_triggers.root
  treeIn: "DF_2270337324663296/O2rtdileptmtree"
  treeOut: "minitree_Pt_2_20"
  cuts: "(fPt > 2. && fPt < 20.)"
  suffix: _Pt_2_20