inputs:
  path: /Users/lucamicheletti/cernbox/JPSI/Run3/MC
  production: LHC24l4
  prefix: AnalysisResults_dq_efficiency
  assocType: time_association
  sigGen: Upsilon1S
  sigRec: mumuFromUpsilon1S
  cuts: [matchedMchMid]
  hlistGen: analysis-same-event-pairing/output
  listGen: MCTruthGen
  histGen: PtMC_MCY
  hlistRec: analysis-same-event-pairing/output
  listRec: PairsMuonSEPM
  histRec: Mass_Pt_Rapidity

outputs:
  path: /Users/lucamicheletti/cernbox/JPSI/Run3/MC