---
prefilter:
  data: /Users/lucamicheletti/GITHUB/dq_run3_analyses/upsilon_flow/data/train_261116/AO2D.root
  treeIn: "DF_2338657052269120/O2rtdileptmtree"
  treeOut: "O2rtdileptmtree"
  cuts: "(fCentFT0C >= 20. && fCentFT0C < 60. && fPt > 2. && fPt < 20. && fCos2DeltaPhi > -1. && fCos2DeltaPhi < 1.)"
  suffix: _Centr_20_60__Pt_2_20